site_name: Audrey üîà
site_url: https://audrey.rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra_css:
  - assets/rulerom.css

extra:
  analytics:
    provider: yandex
    property: 107052211

nav:
  - 'üèõÔ∏è –ì–ª–∞–≤–Ω–∞—è': index.md
  - 'üîà –ú–∞–ª—ã—à':
    - '–û–±–∑–æ—Ä': malysh/index.md
    - '–£—Å–∏–ª–∏—Ç–µ–ª–∏': malysh/amps.md
    - '–ñ–µ–ª–µ–∑–æ': malysh/iron.md
  - 'üß† –õ–∞–º–ø–æ–≤–∞—è –î–µ—Ü–∏–º–∞': decima.md
  - 'üìú –õ–∏—Ü–µ–Ω–∑–∏—è': LICENSE.md
  - 'üìì Log':
    - '–û–±–∑–æ—Ä': log/index.md
    - '2026':
      - '2026 –û–±–∑–æ—Ä': log/2026/index.md
      - '–Ø–Ω–≤–∞—Ä—å': log/2026/01.md
      - '–§–µ–≤—Ä–∞–ª—å': log/2026/02.md
      - '–ú–∞—Ä—Ç': log/2026/03.md
      - '–ê–ø—Ä–µ–ª—å': log/2026/04.md
      - '–ú–∞–π': log/2026/05.md
      - '–ò—é–Ω—å': log/2026/06.md
      - '–ò—é–ª—å': log/2026/07.md
      - '–ê–≤–≥—É—Å—Ç': log/2026/08.md
      - '–°–µ–Ω—Ç—è–±—Ä—å': log/2026/09.md
      - '–û–∫—Ç—è–±—Ä—å': log/2026/10.md
      - '–ù–æ—è–±—Ä—å': log/2026/11.md
      - '–î–µ–∫–∞–±—Ä—å': log/2026/12.md
